controller_list:
  - name: fake_arm_controller
    joints:
      - joint_base_top
      - joint_arm_lower
      - joint_arm_upper
      - joint_lastlink
  - name: fake_fingers_controller
    joints:
      - fingerleft_tohand
      - fingerright_tohand
initial:  # Define initial robot poses.
  - group: arm
    pose: random
  - group: fingers
    pose: f_closed