# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: random
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_base_top
    - joint_arm_lower
    - joint_arm_upper
    - joint_lastlink
    - fingerleft_tohand
    - fingerright_tohand
    - bwl_joint
    - bwr_joint
    - fwl_joint
    - fwr_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - joint_base_top
    - joint_arm_lower
    - joint_arm_upper
    - joint_lastlink
  gains:
    joint_base_top:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_arm_lower:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_arm_upper:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_lastlink:
      p: 100
      d: 1
      i: 1
      i_clamp: 1